#ifndef INITIALIZATION_H_
#define INITIALIZATION_H_

#define PWM_ACTIVE				0
#define ETHERNET_ACTIVE			0
#define PHOTO_ELECTRIC_ACTIVE	0
#define RANGING_SENSORS_ACTIVE	0
#define SMOOSHED_ONE_ACTIVE		0
#define SMOOSHED_TWO_ACTIVE		0
#define GATHER_DATA_ACTIVE		(RANGING_SENSORS_ACTIVE || SMOOSHED_ONE_ACTIVE || SMOOSHED_TWO_ACTIVE)
#define GPIO_INT_ACTIVE			(ETHERNET_ACTIVE || PHOTO_ELECTRIC_ACTIVE)
#define SDCARD_ACTIVE			1

#endif
